/*
 * external_interrupt_config.h
 *
 *  Created on: Sep 20, 2022
 *      Author: Nada Essam
 */

#ifndef EXTERNAL_INTERRUPT_CONFIG_H_
#define EXTERNAL_INTERRUPT_CONFIG_H_

typedef enum {
	EXTI0,
	EXTI1,
	EXTI2
}EXTI_type;

#define DISABLE 0
#define ENABLE 1

#define EXT_INT0_MODE	 ENABLE
#define EXT_INT1_MODE	 DISABLE
#define EXT_INT2_MODE	 DISABLE

#define LOW_LEVEL_TRIG  	0
#define ANY_LOGIC_TRIG		1
#define RAISING_EDGE_TRIG	2
#define FALLING_EDGE_TRIG	3
#define INTERRUPT_DISABLED	4

//SELECT SENSE CONTROL MODE
#define INT0_SENSE_MODE  	RAISING_EDGE_TRIG
#define INT1_SENSE_MODE  	INTERRUPT_DISABLED
#define INT2_SENSE_MODE  	INTERRUPT_DISABLED
#endif /* EXTERNAL_INTERRUPT_CONFIG_H_ */
